CREATE TABLE IF NOT EXISTS users(
  id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  name text NOT NULL CHECK (name <> ''),
  last_name text NOT NULL CHECK (last_name <> ''),
  date_born date NOT NULL
);

INSERT INTO users(name, last_name, date_born) VALUES('Jess Dario', 'Ortega Zapata', '2012-12-01');

INSERT INTO users(name, last_name, date_born) VALUES('Julio Cesar', 'Quispe Atencios', '2008-11-15');

INSERT INTO users(name, last_name, date_born) VALUES('Juanita Mary', 'Suárez Quispe', '1998-05-11');